version: "3.8"

services:
  vsftpd:
    image: vsftpd_local:latest
    restart: no
    container_name: vsftpd
    # network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile
    # command: ["sleep", "infinity"]
    environment:
      - FTP_USER
      - FTP_PASSWORD
    volumes:
      - ./conf/vsftpd.conf:/etc/vsftpd/vsftpd.conf
      - ./cert:/opt/ftp-cert
      - ./data:/opt/ftp-data
    ports:
      - "2121:2121"
      - "2020:2020"
      - "34000-34001:34000-34001"
